executor: LocalExecutor

config:
  webserver:
    expose_config: 'True'

webserver:
  service:
    type: NodePort
triggerer:
  securityContext:
    runAsUser: 0
    fsGroup: 0
    runAsGroup: 0
scheduler:
  securityContext:
    runAsUser: 0
    fsGroup: 0
    runAsGroup: 0
  extraVolumeMounts:
    - name: airflow-datalake
      mountPath: /src/data
  extraVolumes:
    - name: airflow-datalake
      hostPath:
        path: /src/data

dags:
  persistence:
    enabled: true

postgresql:
  enabled: false

extraEnvFrom: |
  - secretRef:
      name: airflow-environment-variables